### ISSUE TITLE
Wrong paper name

### ISSUE THREAD

**Issue by RaymondWang987** [yuchenlichuck/CVPR2022#1]
Wnet: Audio-Guided Video Semantic Segmentation via Wavelet-Based Cross-Modal Denoising Networks

the paper is Wnet: Audio-Guided **Video Object Segmentation** via Wavelet-Based Cross-Modal Denoising Networks
https://github.com/asudahkzj/Wnet

**Comment by yuchenlichuck** [comment]
THank you for sharing!
